apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bluesky-pds.fullname" . }}
  labels:
    {{- include "bluesky-pds.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bluesky-pds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bluesky-pds.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bluesky-pds.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PDS_HOSTNAME
              value: {{ .Values.global.hostname }}
            - name: PDS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "bluesky-pds.fullname" . }}-pds-keys
                  key: PDS_JWT_SECRET
            - name: PDS_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "bluesky-pds.fullname" . }}-pds-keys
                  key: PDS_ADMIN_EMAIL
            - name: PDS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "bluesky-pds.fullname" . }}-pds-keys
                  key: PDS_ADMIN_PASSWORD
            - name: PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: {{ include "bluesky-pds.fullname" . }}-pds-keys
                  key: PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- if .valueFrom.secretKeyRef }}
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
                {{- else if .valueFrom.configMapKeyRef }}
                configMapKeyRef:
                  name: {{ .valueFrom.configMapKeyRef.name }}
                  key: {{ .valueFrom.configMapKeyRef.key }}
                {{- end }}
              {{- end }}
            {{- end }}
          ports:
            {{- range .Values.ports }}
            - name: {{ .name }}
              protocol: {{ .protocol }}
              containerPort: {{ .containerPort }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.dataVolumeConfiguration.mountPath }}
              readOnly: false
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "bluesky-pds.fullname" . }}-data-config-pvc
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
