{{- if .Values.persistentVolumes }}
{{- range $name, $pv := .Values.persistentVolumes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $name }}
spec:
  storageClassName: {{ $pv.storageClassName }}
  capacity:
    storage: {{ $pv.capacity }}
  accessModes:
    {{- range $pv.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if $pv.hostPath }}
  hostPath:
    path: {{ $pv.hostPath }}
  {{- else if $pv.nfs }}
  nfs:
    server: {{ $pv.nfs.server }}
    path: {{ $pv.nfs.path }}
  {{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "bluesky-pds.fullname" . }}-data-volume
spec:
  storageClassName: {{ .Values.dataVolumeConfiguration.storageClassName }}
  capacity:
    storage: {{ .Values.dataVolumeConfiguration.size }}
  accessModes:
    {{- range .Values.dataVolumeConfiguration.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .Values.dataVolumeConfiguration.hostPath }}
  hostPath:
    path: {{ .Values.dataVolumeConfiguration.hostPath }}
  {{- else if .Values.dataVolumeConfiguration.nfs }}
  nfs:
    server: {{ .Values.dataVolumeConfiguration.nfs.server }}
    path: {{ .Values.dataVolumeConfiguration.nfs.path }}
  {{- end }}
{{- end }}
{{- end }}