{{- if eq .Values.global.configuration.secretStore "1password" }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "bluesky-pds.fullname" . }}-pds-keys
spec:
  itemPath: {{ .Values.global.configuration.secretPath }}
{{- end }}
{{- if eq .Values.global.configuration.secretStore "generic" }}
apiVersion: onepassword.com/v1
kind: Secret
metadata:
  name: {{ include "bluesky-pds.fullname" . }}-pds-keys
type: Opaque
spec:
  data:
    {{- range $key, $value := .Values.global.configuration.secretData }}
    {{ $key }}: {{ $value | b64enc }}
    {{- end }}
{{- end }}