apiVersion: {{ if eq .Values.global.configuration.secretStore "1password" }}onepassword.com/v1{{ else }}v1{{ end }}
kind: {{ if eq .Values.global.configuration.secretStore "1password" }}OnePasswordItem{{ else }}Secret{{ end }}
metadata:
  name: {{ include "bluesky-pds.fullname" . }}-pds-keys
{{- if eq .Values.global.configuration.secretStore "generic" }}
type: Opaque
{{- end }}
spec:
{{- if eq .Values.global.configuration.secretStore "1password" }}
  itemPath: {{ .Values.global.configuration.secretPath }}
{{- end }}
{{- if eq .Values.global.configuration.secretStore "generic" }}
  data:
    {{- range $key, $value := .Values.global.configuration.secretData }}
    {{ $key }}: {{ $value | b64enc }}
    {{- end }}
{{- end }}
