{{- if .Values.tunnel.enabled }}
apiVersion: {{ if eq .Values.tunnel.credentialBackend "1password" }}onepassword.com/v1{{ else }}v1{{ end }}
kind: {{ if eq .Values.tunnel.credentialBackend "1password" }}OnePasswordItem{{ else }}Secret{{ end }}
metadata:
  name: {{ include "bluesky-pds.fullname" . }}-tunnel-credentials
spec:
{{- if eq .Values.tunnel.credentialBackend "1password" }}
  itemPath: {{ .Values.tunnel.secretPath }}
{{- else }}
  data:
    credentials.json: {{ .Values.tunnel.credentialsFile | b64enc | quote }}
{{- end }}
{{- end }}