{{- if and .Values.tunnel.enabled (eq .Values.tunnel.credentialBackend "1password") -}}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "bluesky-pds.fullname" . }}-tunnel-credentials
spec:
  itemPath: {{ .Values.tunnel.secretPath }}
{{- end -}}