apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
subjects:
  - kind: ServiceAccount
    name: "{{ include "tailscale.serviceAccountName" . }}"
roleRef:
  kind: Role
  name: {{ include "tailscale.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
