{{- if (eq .Values.credentials.backend "1password") -}}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "tailscale.fullname" . }}-auth
spec:
  itemPath: {{ .Values.credentials.secretPath }}
{{- end -}}